name: Java Code Style Check

on:
  pull_request:
    branches:
      - '**'

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Step 4: Run Checkstyle using Maven
      - name: Run Checkstyle
        run: mvn verify
        continue-on-error: true  # Allow this step to fail without failing the entire workflow

      # Step 5: Report Checkstyle status
      - name: Check if Checkstyle passed
        if: ${{ failure() }}
        run: |
          echo "Checkstyle found issues, but it's expected."
          exit 0
